#include "stdafx.h"

DECLARE_COMPONENT_VERSION(
    "R128 \xE3\x83\xAA\xE3\x82\xA2\xE3\x83\xAB\xE3\x82\xBF\xE3\x82\xA4\xE3\x83\xA0\xE9\x9F\xB3\xE9\x87\x8F\xE3\x83\x8E\xE3\x83\xBC\xE3\x83\x9E\xE3\x83\xA9\xE3\x82\xA4\xE3\x82\xB6\xE3\x83\xBC",
    "1.10.0",
    "R128-based real-time loudness normalizer for foobar2000.\n"
    "foobar2000用のR128ベース・リアルタイム音量ノーマライザーです。\n"
    "\n"
    "Author: Maximum\n"
    "Copyright (c) 2026 Maximum\n"
    "License: MIT License\n"
    "\n"
    "v1.10.0 adds user presets stored separately from DSP preset format v7.\n"
    "The current settings can be saved under a Unicode name, loaded,\n"
    "overwritten, renamed, or deleted. The seven built-in presets remain\n"
    "read-only, and existing DSP settings and component GUIDs are unchanged.\n"
    "\n"
    "v1.10.0では、現在の全設定に名前を付けて保存できる\n"
    "ユーザープリセットを追加しました。呼出、上書き、名前変更、削除に対応し、\n"
    "日本語・英語を含む名前を使用できます。既存7プリセットは変更不可のまま、\n"
    "DSP設定形式v7、既存設定、コンポーネントGUIDも変更しません。\n"
    "\n"
    "v1.9.0 adds a lightweight trend graph for the currently playing track.\n"
    "It records Short-term loudness, total applied gain, automatic attenuation,\n"
    "and processed True Peak about once per second. Red event markers show\n"
    "where automatic control activated. Drawing runs only while the graph\n"
    "window is open, and the real-time audio thread performs no graph work.\n"
    "\n"
    "v1.9.0では、再生中の1曲だけを対象とする軽量な推移グラフを追加しました。\n"
    "Short-termラウドネス、適用中の総ゲイン、自動減衰量、処理後True Peakを\n"
    "約1秒ごとに記録し、自動制御の発動位置を赤い縦線で表示します。\n"
    "描画はグラフ画面を開いている間だけ行い、リアルタイム音声処理スレッドでは\n"
    "グラフ用の記録・描画を行いません。\n"
    "\n"
    "v1.8.0 adds a persistent Automatic-Control History for up to 100 tracks.\n"
    "It records playback time, title and artist, preset, trigger reason,\n"
    "maximum automatic attenuation, activation count, adjustment-limit\n"
    "status, and safe recovery. History can be copied or deleted from the\n"
    "Diagnostics page without writing from the real-time audio thread.\n"
    "\n"
    "v1.8.0では、自動制御が発動した最新100曲の履歴を追加しました。\n"
    "再生日時、曲名／アーティスト、プリセット、発動理由、最大自動減衰量、\n"
    "発動回数、調整上限、安全復帰を一覧で確認・コピー・削除できます。\n"
    "リアルタイム音声処理中には履歴のディスク書き込みを行いません。\n"
    "\n"
    "v1.7.0 makes automatic safety control easier to understand by showing\n"
    "Monitoring and Auto-adjusting states, the trigger reason, and the\n"
    "positive automatic attenuation amount in diagnostics. The state returns\n"
    "to Normal after safe recovery.\n"
    "\n"
    "v1.7.0では、自動安全制御の状態を「監視中」「自動調整中」まで\n"
    "分かりやすく表示し、発動理由と実施した自動減衰量を診断へ表示します。\n"
    "安全復帰後の現在の処理状態は「正常」に戻ります。\n"
    "\n"
    "v1.6.1 keeps the settings window accessible at 200-250% scaling,\n"
    "improves live theme switching and tooltip scaling at high DPI,\n"
    "and completes the English text for the processing-strength range.\n"
    "\n"
    "v1.6.1では、200～250%表示時の設定画面をスクロール対応し、\n"
    "画面を開いたままテーマを切り替えた際のツールチップ配色追従と、\n"
    "高DPIでのツールチップ幅を改善しました。\n"
    "処理強度の範囲表示に残っていた英語化漏れも修正しました。\n"
    "\n"
    "v1.6.0 adds Automatic / Japanese / English display-language selection.\n"
    "The settings UI, diagnostics, help, glossary, messages, tooltips,\n"
    "license information, DSP name, and Playback menu support English.\n"
    "\n"
    "v1.6.0では、表示言語の自動／日本語／English切り替えと、\n"
    "設定画面、診断、ヘルプ、用語集、各メッセージ、ツールチップ、\n"
    "ライセンス、DSP名、Playbackメニューの英語表示に対応しました。\n"
    "言語設定はDSPプリセットとは別に保存されるため、\n"
    "設定保存形式v7と既存プリセットの互換性を維持します。\n"
    "\n"
    "v1.5.4では、処理負荷をリアルタイム監視し、\n"
    "要調整相当が続いた場合に自動安全補正を行います。\n"
    "現在の処理状態は正常／要調整／自動調整中／調整上限で表示し、\n"
    "安全な状態が続くと自動的に正常へ戻ります。\n"
    "\n"
    "v1.5.1では、項目ヘルプとライセンス・クレジット画面も\n"
    "foobar2000本体のライト／ダーク／レトロ表示へ自動追従します。\n"
    "\n"
    "v1.5.0では、foobar2000本体のライト／ダーク表示へ\n"
    "設定画面が自動追従するようになりました。\n"
    "PlaybackメニューからDSP Managerを経由せずに\n"
    "設定画面を直接開けるようになりました。\n"
    "直接開いた画面はfoobar2000より手前を保ったまま操作できます。\n"
    "背後のfoobar2000も操作でき、ほかのアプリには最前面固定しません。\n"
    "メインメニューコマンドはキーボードショートカットにも割り当て可能です。\n"
    "\n"
    "DSPが未登録または複数登録されている場合は、\n"
    "誤変更を防ぐため案内を表示して設定を変更しません。\n"
    "\n"
    "音声処理、測定計算、プリセット値、設定保存形式、\n"
    "コンポーネントGUIDはv1.4.1と同一です。\n"
    "\n"
    "確認済み表示環境：1920x1080、Windows表示倍率150%。\n"
    "\n"
    "Conceptually based in part on the prior work\n"
    "EBU R128 Normalizer by mudlord.\n"
    "This implementation was independently written.\n"
    "\n"
    "See license.txt and THIRD-PARTY-NOTICES.txt for full notices."
);

VALIDATE_COMPONENT_FILENAME("foo_r128_normalizer.dll");
