#include "stdafx.h"

DECLARE_COMPONENT_VERSION(
    "R128 \xE3\x83\xAA\xE3\x82\xA2\xE3\x83\xAB\xE3\x82\xBF\xE3\x82\xA4\xE3\x83\xA0\xE9\x9F\xB3\xE9\x87\x8F\xE3\x83\x8E\xE3\x83\xBC\xE3\x83\x9E\xE3\x83\xA9\xE3\x82\xA4\xE3\x82\xB6\xE3\x83\xBC",
    "1.5.4",
    "foobar2000用のR128ベース・リアルタイム音量ノーマライザーです。\n"
    "\n"
    "Author: Maximum\n"
    "Copyright (c) 2026 Maximum\n"
    "License: MIT License\n"
    "\n"
    "v1.5.4では、処理負荷をリアルタイム監視し、\n"
    "要調整相当が続いた場合に自動安全補正を行います。\n"
    "現在の処理状態は正常／要調整／自動調整中／調整上限で表示し、\n"
    "安全な状態が続くと自動的に正常へ戻ります。\n"
    "\n"
    "v1.5.1では、項目ヘルプとライセンス・クレジット画面も\n"
    "foobar2000本体のライト／ダーク／レトロ表示へ自動追従します。\n"
    "\n"
    "v1.5.0では、foobar2000本体のライト／ダーク表示へ\n"
    "設定画面が自動追従するようになりました。\n"
    "PlaybackメニューからDSP Managerを経由せずに\n"
    "設定画面を直接開けるようになりました。\n"
    "直接開いた画面はfoobar2000より手前を保ったまま操作できます。\n"
    "背後のfoobar2000も操作でき、ほかのアプリには最前面固定しません。\n"
    "メインメニューコマンドはキーボードショートカットにも割り当て可能です。\n"
    "\n"
    "DSPが未登録または複数登録されている場合は、\n"
    "誤変更を防ぐため案内を表示して設定を変更しません。\n"
    "\n"
    "音声処理、測定計算、プリセット値、設定保存形式、\n"
    "コンポーネントGUIDはv1.4.1と同一です。\n"
    "\n"
    "確認済み表示環境：1920x1080、Windows表示倍率150%。\n"
    "\n"
    "Conceptually based in part on the prior work\n"
    "EBU R128 Normalizer by mudlord.\n"
    "This implementation was independently written.\n"
    "\n"
    "See license.txt and THIRD-PARTY-NOTICES.txt for full notices."
);

VALIDATE_COMPONENT_FILENAME("foo_r128_normalizer.dll");
